### ISSUE TITLE
IVAN version number on the high score server

### ISSUE THREAD

**Issue by ryfactor** [emlai/ivan-hall-of-fame#2]
Do you know if it will be possible to add the IVAN version number to the high score server page? It means that players will be able to distinguish between victories over successive releases of the game.

**Comment by emillaine** [comment]
Yeah I'm going to add this feature at some point. It's pretty high on the todo list. 👍

**Comment by emillaine** [comment]
Actually I just implemented it, should work now! (Still missing authentication though.)
